2013-07-06 17:47:45 Error: [MissingControllerException] Controller class TasksController could not be found.
Exception Attributes: array (
  'class' => 'TasksController',
  'plugin' => NULL,
)
Request URL: /cakephp/tasks/
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-07-06 18:12:52 Error: [MissingViewException] View file "E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Tasks\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\ProgramFiles\\xampp\\htdocs\\cakephp\\app\\View\\Tasks\\index.ctp',
)
Request URL: /cakephp/tasks/
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\View\View.php(468): View->_getViewFileName('index')
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(948): View->render('index', NULL)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\TasksController.php(12): Controller->render('index')
#3 [internal function]: TasksController->index()
#4 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(486): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#5 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#6 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#7 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2013-07-06 18:13:07 Error: [MissingViewException] View file "E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Tasks\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\ProgramFiles\\xampp\\htdocs\\cakephp\\app\\View\\Tasks\\index.ctp',
)
Request URL: /cakephp/tasks/index
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\View\View.php(468): View->_getViewFileName('index')
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(948): View->render('index', NULL)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\TasksController.php(12): Controller->render('index')
#3 [internal function]: TasksController->index()
#4 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(486): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#5 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#6 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#7 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2013-07-06 18:52:41 Error: Fatal Error (4): syntax error, unexpected 'endforeach' (T_ENDFOREACH) in [E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Tasks\index.ctp, line 34]
2013-07-06 18:52:41 Error: [FatalErrorException] syntax error, unexpected 'endforeach' (T_ENDFOREACH)
Request URL: /cakephp/tasks/index
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\ProgramFiles...', 34)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\ProgramFiles...', 34, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\ProgramFiles...', 34, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-07-06 18:56:38 Error: Fatal Error (4): syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING) in [E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Tasks\index.ctp, line 29]
2013-07-06 18:56:38 Error: [FatalErrorException] syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING)
Request URL: /cakephp/tasks/index
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\ProgramFiles...', 29)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\ProgramFiles...', 29, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\ProgramFiles...', 29, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-07-06 19:07:34 Error: Fatal Error (1): Call to undefined method SessionComponent::setFlush() in [E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\TasksController.php, line 30]
2013-07-06 19:07:34 Error: [InternalErrorException] Internal Server Error
Request URL: /cakephp/Tasks/done/1
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'E:\ProgramFiles...', 30)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'E:\ProgramFiles...', 30, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'E:\ProgramFiles...', 30, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-07-06 19:08:02 Error: Fatal Error (1): Call to undefined method SessionComponent::setFlush() in [E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\TasksController.php, line 30]
2013-07-06 19:08:02 Error: [InternalErrorException] Internal Server Error
Request URL: /cakephp/Tasks/done/2
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'E:\ProgramFiles...', 30)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'E:\ProgramFiles...', 30, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'E:\ProgramFiles...', 30, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-07-06 19:08:38 Error: Fatal Error (1): Call to undefined method SessionComponent::setFlush() in [E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\TasksController.php, line 30]
2013-07-06 19:08:38 Error: [InternalErrorException] Internal Server Error
Request URL: /cakephp/Tasks/done/1
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'E:\ProgramFiles...', 30)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'E:\ProgramFiles...', 30, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'E:\ProgramFiles...', 30, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-07-06 19:42:54 Error: Fatal Error (4): syntax error, unexpected 'method' (T_STRING) in [E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Tasks\create.ctp, line 2]
2013-07-06 19:42:54 Error: [InternalErrorException] Internal Server Error
Request URL: /cakephp/Tasks/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\ProgramFiles...', 2)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\ProgramFiles...', 2, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\ProgramFiles...', 2, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-07-06 19:44:58 Error: Fatal Error (4): syntax error, unexpected 'method' (T_STRING) in [E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Tasks\create.ctp, line 2]
2013-07-06 19:44:58 Error: [InternalErrorException] Internal Server Error
Request URL: /cakephp/Tasks/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\ProgramFiles...', 2)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\ProgramFiles...', 2, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\ProgramFiles...', 2, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-07-06 19:45:43 Error: Fatal Error (4): syntax error, unexpected 'method' (T_STRING) in [E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Tasks\create.ctp, line 2]
2013-07-06 19:45:43 Error: [FatalErrorException] syntax error, unexpected 'method' (T_STRING)
Request URL: /cakephp/Tasks/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\ProgramFiles...', 2)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\ProgramFiles...', 2, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\ProgramFiles...', 2, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-07-13 18:53:25 Error: Fatal Error (4): syntax error, unexpected 'endforeach' (T_ENDFOREACH) in [E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Tasks\index.ctp, line 40]
2013-07-13 18:53:25 Error: [FatalErrorException] syntax error, unexpected 'endforeach' (T_ENDFOREACH)
Request URL: /cakephp/tasks/index
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\ProgramFiles...', 40)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\ProgramFiles...', 40, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\ProgramFiles...', 40, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-07-13 21:06:44 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'sava' at line 1
Request URL: /cakephp/Tasks/edit/3
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('sava', Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(669): DboSource->execute('sava', Array, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(612): DboSource->fetchAll('sava', Array, Array)
#4 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Model\Model.php(800): DboSource->query('sava', Array, Object(Task))
#5 E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\TasksController.php(86): Model->__call('sava', Array)
#6 E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\TasksController.php(86): Task->sava(Array)
#7 [internal function]: TasksController->edit('3')
#8 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(486): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#9 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#10 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#11 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2013-07-20 17:53:20 Error: [MissingViewException] View file "E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Users\login.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\ProgramFiles\\xampp\\htdocs\\cakephp\\app\\View\\Users\\login.ctp',
)
Request URL: /cakephp/users/login
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(948): View->render(NULL, NULL)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(194): Controller->render()
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-07-20 18:53:21 Error: Fatal Error (4): syntax error, unexpected ')', expecting ',' or ';' in [E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\AppController.php, line 52]
2013-07-20 18:53:21 Error: [FatalErrorException] syntax error, unexpected ')', expecting ',' or ';'
Request URL: /cakephp/users/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\ProgramFiles...', 52)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\ProgramFiles...', 52, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\ProgramFiles...', 52, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-07-20 18:55:14 Error: Fatal Error (1): Call to a member function passwords() on a non-object in [E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\UsersController.php, line 32]
2013-07-20 18:55:14 Error: [FatalErrorException] Call to a member function passwords() on a non-object
Request URL: /cakephp/Users/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\ProgramFiles...', 32)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\ProgramFiles...', 32, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\ProgramFiles...', 32, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-07-20 18:56:02 Error: Fatal Error (1): Call to a member function passwords() on a non-object in [E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\UsersController.php, line 32]
2013-07-20 18:56:02 Error: [FatalErrorException] Call to a member function passwords() on a non-object
Request URL: /cakephp/Users/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\ProgramFiles...', 32)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\ProgramFiles...', 32, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\ProgramFiles...', 32, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-07-20 18:56:12 Error: Fatal Error (1): Call to a member function passwords() on a non-object in [E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\UsersController.php, line 32]
2013-07-20 18:56:12 Error: [FatalErrorException] Call to a member function passwords() on a non-object
Request URL: /cakephp/Users/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\ProgramFiles...', 32)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\ProgramFiles...', 32, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\ProgramFiles...', 32, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-07-20 18:56:16 Error: Fatal Error (1): Call to a member function passwords() on a non-object in [E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\UsersController.php, line 32]
2013-07-20 18:56:16 Error: [FatalErrorException] Call to a member function passwords() on a non-object
Request URL: /cakephp/Users/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\ProgramFiles...', 32)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\ProgramFiles...', 32, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\ProgramFiles...', 32, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-07-20 18:58:58 Error: Fatal Error (1): Call to a member function password() on a non-object in [E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\UsersController.php, line 32]
2013-07-20 18:58:58 Error: [FatalErrorException] Call to a member function password() on a non-object
Request URL: /cakephp/Users/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\ProgramFiles...', 32)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\ProgramFiles...', 32, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\ProgramFiles...', 32, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-07-20 19:28:14 Error: [MissingActionException] Action Users::users() could not be found.
Exception Attributes: array (
  'controller' => 'Users',
  'action' => 'users',
)
Request URL: /cakephp/users/users/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Scaffold.php(153): Scaffold->_scaffold(Object(CakeRequest))
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(531): Scaffold->__construct(Object(UsersController), Object(CakeRequest))
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(490): Controller->_getScaffold(Object(CakeRequest))
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#4 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#5 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2013-07-20 19:28:51 Error: [MissingActionException] Action Users::users() could not be found.
Exception Attributes: array (
  'controller' => 'Users',
  'action' => 'users',
)
Request URL: /cakephp/users/users/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Scaffold.php(153): Scaffold->_scaffold(Object(CakeRequest))
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(531): Scaffold->__construct(Object(UsersController), Object(CakeRequest))
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(490): Controller->_getScaffold(Object(CakeRequest))
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#4 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#5 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2013-07-20 19:30:08 Error: [MissingActionException] Action Users::users() could not be found.
Exception Attributes: array (
  'controller' => 'Users',
  'action' => 'users',
)
Request URL: /cakephp/users/users/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Scaffold.php(153): Scaffold->_scaffold(Object(CakeRequest))
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(531): Scaffold->__construct(Object(UsersController), Object(CakeRequest))
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(490): Controller->_getScaffold(Object(CakeRequest))
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#4 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#5 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2013-07-20 19:32:16 Error: [MissingActionException] Action Users::users() could not be found.
Exception Attributes: array (
  'controller' => 'Users',
  'action' => 'users',
)
Request URL: /cakephp/users/users/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Scaffold.php(153): Scaffold->_scaffold(Object(CakeRequest))
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(531): Scaffold->__construct(Object(UsersController), Object(CakeRequest))
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(490): Controller->_getScaffold(Object(CakeRequest))
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#4 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#5 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2013-07-20 19:32:40 Error: [MissingActionException] Action Users::users() could not be found.
Exception Attributes: array (
  'controller' => 'Users',
  'action' => 'users',
)
Request URL: /cakephp/users/users/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Scaffold.php(153): Scaffold->_scaffold(Object(CakeRequest))
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(531): Scaffold->__construct(Object(UsersController), Object(CakeRequest))
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(490): Controller->_getScaffold(Object(CakeRequest))
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#4 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#5 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2013-07-20 19:33:26 Error: [MissingActionException] Action Users::users() could not be found.
Exception Attributes: array (
  'controller' => 'Users',
  'action' => 'users',
)
Request URL: /cakephp/users/users/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Scaffold.php(153): Scaffold->_scaffold(Object(CakeRequest))
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(531): Scaffold->__construct(Object(UsersController), Object(CakeRequest))
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(490): Controller->_getScaffold(Object(CakeRequest))
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#4 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#5 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2013-07-20 19:34:56 Error: [MissingActionException] Action Users::users() could not be found.
Exception Attributes: array (
  'controller' => 'Users',
  'action' => 'users',
)
Request URL: /cakephp/users/users/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Scaffold.php(153): Scaffold->_scaffold(Object(CakeRequest))
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(531): Scaffold->__construct(Object(UsersController), Object(CakeRequest))
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(490): Controller->_getScaffold(Object(CakeRequest))
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#4 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#5 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2013-07-20 19:35:08 Error: [MissingActionException] Action Users::users() could not be found.
Exception Attributes: array (
  'controller' => 'Users',
  'action' => 'users',
)
Request URL: /cakephp/users/users/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Scaffold.php(153): Scaffold->_scaffold(Object(CakeRequest))
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(531): Scaffold->__construct(Object(UsersController), Object(CakeRequest))
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(490): Controller->_getScaffold(Object(CakeRequest))
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#4 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#5 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2013-07-20 19:35:13 Error: [MissingControllerException] Controller class UsersControllerController could not be found.
Exception Attributes: array (
  'class' => 'UsersControllerController',
  'plugin' => NULL,
)
Request URL: /cakephp/UsersController/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-07-20 19:35:58 Error: [MissingActionException] Action Users::Users() could not be found.
Exception Attributes: array (
  'controller' => 'Users',
  'action' => 'Users',
)
Request URL: /cakephp/users/Users/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Scaffold.php(153): Scaffold->_scaffold(Object(CakeRequest))
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(531): Scaffold->__construct(Object(UsersController), Object(CakeRequest))
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(490): Controller->_getScaffold(Object(CakeRequest))
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#4 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#5 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2013-07-20 19:36:18 Error: [MissingActionException] Action Users::Users() could not be found.
Exception Attributes: array (
  'controller' => 'Users',
  'action' => 'Users',
)
Request URL: /cakephp/users/Users/create
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Scaffold.php(153): Scaffold->_scaffold(Object(CakeRequest))
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(531): Scaffold->__construct(Object(UsersController), Object(CakeRequest))
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(490): Controller->_getScaffold(Object(CakeRequest))
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#4 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#5 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
2013-07-20 20:05:24 Error: [MissingViewException] View file "E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Tasks\all_list.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\ProgramFiles\\xampp\\htdocs\\cakephp\\app\\View\\Tasks\\all_list.ctp',
)
Request URL: /cakephp/tasks/allList
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(948): View->render(NULL, NULL)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(194): Controller->render()
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#4 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-07-20 20:11:20 Error: [MissingViewException] View file "E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Tasks\all_list.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\ProgramFiles\\xampp\\htdocs\\cakephp\\app\\View\\Tasks\\all_list.ctp',
)
Request URL: /cakephp/tasks/allList
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\View\View.php(468): View->_getViewFileName('allList')
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(948): View->render('allList', NULL)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\TasksController.php(22): Controller->render('allList')
#3 [internal function]: TasksController->alllist()
#4 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(486): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#5 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#6 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#7 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2013-07-20 20:11:35 Error: [MissingViewException] View file "E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Tasks\all_list.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\ProgramFiles\\xampp\\htdocs\\cakephp\\app\\View\\Tasks\\all_list.ctp',
)
Request URL: /cakephp/tasks/alllist
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\View\View.php(468): View->_getViewFileName('allList')
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(948): View->render('allList', NULL)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\TasksController.php(22): Controller->render('allList')
#3 [internal function]: TasksController->alllist()
#4 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(486): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#5 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#6 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#7 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2013-07-20 20:13:03 Error: [MissingViewException] View file "E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Tasks\all_list.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\ProgramFiles\\xampp\\htdocs\\cakephp\\app\\View\\Tasks\\all_list.ctp',
)
Request URL: /cakephp/tasks/alllist
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\View\View.php(468): View->_getViewFileName('allList')
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(948): View->render('allList', NULL)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\TasksController.php(22): Controller->render('allList')
#3 [internal function]: TasksController->alllist()
#4 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(486): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#5 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#6 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#7 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2013-07-20 20:13:10 Error: [MissingViewException] View file "E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Tasks\all_list.ctp" is missing.
Exception Attributes: array (
  'file' => 'E:\\ProgramFiles\\xampp\\htdocs\\cakephp\\app\\View\\Tasks\\all_list.ctp',
)
Request URL: /cakephp/tasks/alllist
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\View\View.php(468): View->_getViewFileName('allList')
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(948): View->render('allList', NULL)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\TasksController.php(22): Controller->render('allList')
#3 [internal function]: TasksController->alllist()
#4 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(486): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#5 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#6 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#7 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2013-08-03 18:03:38 Error: Fatal Error (1): Call to a member function user() on a non-object in [E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\Component\NameComponent.php, line 8]
2013-08-03 18:03:38 Error: [FatalErrorException] Call to a member function user() on a non-object
Request URL: /cakephp/tasks/index
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\ProgramFiles...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\ProgramFiles...', 8, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\ProgramFiles...', 8, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-03 18:22:19 Error: [MissingHelperException] Helper class TitleHelper could not be found.
Exception Attributes: array (
  'class' => 'TitleHelper',
  'plugin' => false,
)
Request URL: /cakephp/Tasks/index
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\View\HelperCollection.php(63): HelperCollection->load('Title')
#1 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\View\View.php(835): HelperCollection->__isset('Title')
#2 E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Tasks\index.ctp(4): View->__get('Title')
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\View\View.php(947): include('E:\ProgramFiles...')
#4 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\View\View.php(909): View->_evaluate('E:\ProgramFiles...', Array)
#5 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\View\View.php(471): View->_render('E:\ProgramFiles...')
#6 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(948): View->render('index', NULL)
#7 E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\TasksController.php(48): Controller->render('index')
#8 [internal function]: TasksController->index()
#9 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(486): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#10 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#11 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#12 E:\ProgramFiles\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2013-08-03 19:23:41 Error: Fatal Error (4): syntax error, unexpected '}' in [E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\TasksController.php, line 77]
2013-08-03 19:23:41 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /cakephp/Tasks/index
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\ProgramFiles...', 77)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\ProgramFiles...', 77, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\ProgramFiles...', 77, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-03 19:24:07 Error: Fatal Error (1): Call to undefined function mailer() in [E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\TasksController.php, line 40]
2013-08-03 19:24:07 Error: [FatalErrorException] Call to undefined function mailer()
Request URL: /cakephp/Tasks/index
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'E:\ProgramFiles...', 40)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'E:\ProgramFiles...', 40, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'E:\ProgramFiles...', 40, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-03 19:24:54 Error: Fatal Error (1): Class 'CakeEmail' not found in [E:\ProgramFiles\xampp\htdocs\cakephp\app\Controller\TasksController.php, line 67]
2013-08-03 19:24:54 Error: [FatalErrorException] Class 'CakeEmail' not found
Request URL: /cakephp/Tasks/index
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Class 'CakeEmai...', 'E:\ProgramFiles...', 67)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'CakeEmai...', 'E:\ProgramFiles...', 67, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Class 'CakeEmai...', 'E:\ProgramFiles...', 67, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-17 19:10:03 Error: Fatal Error (1): Call to a member function Link() on a non-object in [E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Helper\TitleHelper.php, line 17]
2013-08-17 19:10:03 Error: [FatalErrorException] Call to a member function Link() on a non-object
Request URL: /cakephp/Tasks/edit/2
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\ProgramFiles...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\ProgramFiles...', 17, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\ProgramFiles...', 17, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-17 19:12:31 Error: Fatal Error (1): Call to a member function Link() on a non-object in [E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Helper\TitleHelper.php, line 21]
2013-08-17 19:12:31 Error: [FatalErrorException] Call to a member function Link() on a non-object
Request URL: /cakephp/tasks/index
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\ProgramFiles...', 21)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\ProgramFiles...', 21, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\ProgramFiles...', 21, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-17 19:17:30 Error: Fatal Error (1): Call to a member function Link() on a non-object in [E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Helper\TitleHelper.php, line 21]
2013-08-17 19:17:30 Error: [FatalErrorException] Call to a member function Link() on a non-object
Request URL: /cakephp/tasks/index
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\ProgramFiles...', 21)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\ProgramFiles...', 21, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\ProgramFiles...', 21, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-17 19:21:03 Error: Fatal Error (1): Call to a member function Link() on a non-object in [E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Helper\TitleHelper.php, line 25]
2013-08-17 19:21:03 Error: [FatalErrorException] Call to a member function Link() on a non-object
Request URL: /cakephp/tasks/index
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\ProgramFiles...', 25)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\ProgramFiles...', 25, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\ProgramFiles...', 25, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-17 19:22:17 Error: Fatal Error (1): Call to a member function Link() on a non-object in [E:\ProgramFiles\xampp\htdocs\cakephp\app\View\Helper\TitleHelper.php, line 25]
2013-08-17 19:22:17 Error: [FatalErrorException] Call to a member function Link() on a non-object
Request URL: /cakephp/tasks/index
Stack Trace:
#0 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\ProgramFiles...', 25)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\ProgramFiles...', 25, Array)
#2 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\ProgramFiles...', 25, Array)
#3 E:\ProgramFiles\xampp\htdocs\cakephp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
